#Read in Data

In [3]:
import pandas as pd
data = pd.read_csv('data_cleaned.csv', index_col = 0)
data.head(3)

,country,season,md,team,manager,formation,goals,gd,outcome,points,opp_team,opp_manager,opp_formation,opp_goals,opp_gd,opp_outcome,opp_points,avg_starter_age,total_starter_value
0,Germany,2004,1,1.FC Kaiserslautern,Kurt Jara,4-4-2 double 6,1.0,-2.0,loss,0.0,1.FC Nuremberg,Wolfgang Wolf,4-4-2 Diamond,3.0,2.0,win,3.0,27.818182,15.95
1,Germany,2004,2,1.FC Kaiserslautern,Kurt Jara,3-5-2,1.0,-1.0,loss,0.0,FC Schalke 04,Jupp Heynckes,3-5-2,2.0,1.0,win,3.0,28.000000,16.50
2,Germany,2004,3,1.FC Kaiserslautern,Kurt Jara,4-2-3-1,2.0,-1.0,loss,0.0,VfB Stuttgart,Matthias Sammer,4-4-2 Diamond,3.0,1.0,win,3.0,27.333333,14.20

Drop rows where target variable records are null

In [4]:
data = data[data['total_starter_value'].notna()]
data.head(3)

,country,season,md,team,manager,formation,goals,gd,outcome,points,opp_team,opp_manager,opp_formation,opp_goals,opp_gd,opp_outcome,opp_points,avg_starter_age,total_starter_value
0,Germany,2004,1,1.FC Kaiserslautern,Kurt Jara,4-4-2 double 6,1.0,-2.0,loss,0.0,1.FC Nuremberg,Wolfgang Wolf,4-4-2 Diamond,3.0,2.0,win,3.0,27.818182,15.95
1,Germany,2004,2,1.FC Kaiserslautern,Kurt Jara,3-5-2,1.0,-1.0,loss,0.0,FC Schalke 04,Jupp Heynckes,3-5-2,2.0,1.0,win,3.0,28.000000,16.50
2,Germany,2004,3,1.FC Kaiserslautern,Kurt Jara,4-2-3-1,2.0,-1.0,loss,0.0,VfB Stuttgart,Matthias Sammer,4-4-2 Diamond,3.0,1.0,win,3.0,27.333333,14.20

Identify missing values

In [5]:
data.isnull().sum()

country                   0
season                    0
md                        0
team                      0
manager                  13
formation              3062
goals                     0
gd                        0
outcome                   0
points                    0
opp_team                  0
opp_manager              13
opp_formation          3062
opp_goals                 0
opp_gd                    0
opp_outcome               0
opp_points                0
avg_starter_age           3
total_starter_value       0
dtype: int64

Upon further inspection, AC Ajaccio in the 2005 season are missing manager and formations records. This team and season are therefore dropped from the data.

In [6]:
data = data[data.manager.notnull()]
data.head(3)

,country,season,md,team,manager,formation,goals,gd,outcome,points,opp_team,opp_manager,opp_formation,opp_goals,opp_gd,opp_outcome,opp_points,avg_starter_age,total_starter_value
0,Germany,2004,1,1.FC Kaiserslautern,Kurt Jara,4-4-2 double 6,1.0,-2.0,loss,0.0,1.FC Nuremberg,Wolfgang Wolf,4-4-2 Diamond,3.0,2.0,win,3.0,27.818182,15.95
1,Germany,2004,2,1.FC Kaiserslautern,Kurt Jara,3-5-2,1.0,-1.0,loss,0.0,FC Schalke 04,Jupp Heynckes,3-5-2,2.0,1.0,win,3.0,28.000000,16.50
2,Germany,2004,3,1.FC Kaiserslautern,Kurt Jara,4-2-3-1,2.0,-1.0,loss,0.0,VfB Stuttgart,Matthias Sammer,4-4-2 Diamond,3.0,1.0,win,3.0,27.333333,14.20

Same is done with opposition managers

In [7]:
data = data[data.opp_manager.notnull()]

Identify records where the average starting age is not available.

In [8]:
data[data['avg_starter_age'].isna()]

,country,season,md,team,manager,formation,goals,gd,outcome,points,opp_team,opp_manager,opp_formation,opp_goals,opp_gd,opp_outcome,opp_points,avg_starter_age,total_starter_value
8704,England,2018,38,Liverpool FC,Jürgen Klopp,4-3-3 Attacking,2.0,2.0,win,3.0,Wolverhampton Wanderers,Nuno Espírito Santo,3-5-2 flat,0.0,-2.0,loss,0.0,NaN,0.0
23666,England,2011,38,Manchester City,Roberto Mancini,4-2-3-1,3.0,1.0,win,3.0,Queens Park Rangers,Mark Hughes,4-4-2 double 6,2.0,-1.0,loss,0.0,NaN,0.0
47701,England,2006,38,Manchester United,Sir Alex Ferguson,NaN,0.0,-1.0,loss,0.0,West Ham United,Alan Curbishley,NaN,1.0,1.0,win,3.0,NaN,0.0

As the data is stored by sequentially, these values can be replaced with the previous weeks' from the same team as data is unlikely to change siginificantly from one game to the next.

In [9]:
#Replace with previous values
data['avg_starter_age'].fillna(method='pad', inplace=True)
data.head(3)

<ipython-input-9-b54e09393fa1>:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data['avg_starter_age'].fillna(method='pad', inplace=True)

,country,season,md,team,manager,formation,goals,gd,outcome,points,opp_team,opp_manager,opp_formation,opp_goals,opp_gd,opp_outcome,opp_points,avg_starter_age,total_starter_value
0,Germany,2004,1,1.FC Kaiserslautern,Kurt Jara,4-4-2 double 6,1.0,-2.0,loss,0.0,1.FC Nuremberg,Wolfgang Wolf,4-4-2 Diamond,3.0,2.0,win,3.0,27.818182,15.95
1,Germany,2004,2,1.FC Kaiserslautern,Kurt Jara,3-5-2,1.0,-1.0,loss,0.0,FC Schalke 04,Jupp Heynckes,3-5-2,2.0,1.0,win,3.0,28.000000,16.50
2,Germany,2004,3,1.FC Kaiserslautern,Kurt Jara,4-2-3-1,2.0,-1.0,loss,0.0,VfB Stuttgart,Matthias Sammer,4-4-2 Diamond,3.0,1.0,win,3.0,27.333333,14.20

Null values are re-checked.

In [10]:
data.isnull().sum()

country                   0
season                    0
md                        0
team                      0
manager                   0
formation              3046
goals                     0
gd                        0
outcome                   0
points                    0
opp_team                  0
opp_manager               0
opp_formation          3046
opp_goals                 0
opp_gd                    0
opp_outcome               0
opp_points                0
avg_starter_age           0
total_starter_value       0
dtype: int64

Remove data where formation is null.

In [11]:
data = data[data.formation.notnull()]
data = data[data.opp_formation.notnull()]
data.head(3)

,country,season,md,team,manager,formation,goals,gd,outcome,points,opp_team,opp_manager,opp_formation,opp_goals,opp_gd,opp_outcome,opp_points,avg_starter_age,total_starter_value
0,Germany,2004,1,1.FC Kaiserslautern,Kurt Jara,4-4-2 double 6,1.0,-2.0,loss,0.0,1.FC Nuremberg,Wolfgang Wolf,4-4-2 Diamond,3.0,2.0,win,3.0,27.818182,15.95
1,Germany,2004,2,1.FC Kaiserslautern,Kurt Jara,3-5-2,1.0,-1.0,loss,0.0,FC Schalke 04,Jupp Heynckes,3-5-2,2.0,1.0,win,3.0,28.000000,16.50
2,Germany,2004,3,1.FC Kaiserslautern,Kurt Jara,4-2-3-1,2.0,-1.0,loss,0.0,VfB Stuttgart,Matthias Sammer,4-4-2 Diamond,3.0,1.0,win,3.0,27.333333,14.20

Check to ensure data is now complete

In [12]:
data.isnull().sum()

country                0
season                 0
md                     0
team                   0
manager                0
formation              0
goals                  0
gd                     0
outcome                0
points                 0
opp_team               0
opp_manager            0
opp_formation          0
opp_goals              0
opp_gd                 0
opp_outcome            0
opp_points             0
avg_starter_age        0
total_starter_value    0
dtype: int64

In [13]:
data.to_csv('data_pre_processed.csv')